### PR TITLE
#90 - user profile

### LINKED ISSUE #90: User profile
Each user should have profile with information about his birthday and last activity.

### LINKED ISSUE #124: Refreshing at vacation calendar
**Describe the bug**
When I came to the `vacation calendar` page, I clicked the `dzisiaj` button and page refreshed - any change did not came with that refresh. Additional thing is this when I change year, I have `dzisiaj` string in button.

**To Reproduce**
    1. Go to the calendar vacation page (`/vacation/calendar`).
    2. Start non-stop clicking on the 'dzisiaj' button.
    3. Open network developer tool in browser.
    4. Repeat step two.

**Expected behavior**
Page should not refresh.

### PR DESCRIPTION
**Pull request by Baakoma**
It should close #90 and fixes #124

Also, there are many ui fixes.

### CODE REVIEW

File: app/Architecture/ExceptionHandler.php [hunk 1]
```diff
@@ -21,7 +21,15 @@ public function render($request, Throwable $e): Response
     {
         $response = parent::render($request, $e);
 
-        if (app()->environment("production") && in_array($response->status(), [500, 503, 429, 419, 404, 403, 401], true)) {
+        if (!app()->environment("production")) {
+            return $response;
+        }
+
+        if ($response->status() === 405) {
```
Comment (krzysztofrewak) [inline app/Architecture/ExceptionHandler.php:28]: Could you use `Response::METHOD_NOT_ALLOWED` and other consts instead of magic numbers?

File: app/Domain/Notifications/VacationRequestWaitsForApprovalNotification.php [hunk 2]
```diff
@@ -43,7 +43,7 @@ public function toMail(): MailMessage
 
     protected function buildMailMessage(string $url): MailMessage
     {
-        $user = $this->user->first_name;
+        $user = $this->user->profile->first_name;
```
Comment (krzysztofrewak) [inline app/Domain/Notifications/VacationRequestWaitsForApprovalNotification.php:46]: Why `first_name`, but `fullName`?

File: app/Infrastructure/Console/Commands/MoveUserDataToProfile.php [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+class MoveUserDataToProfile extends Command
+{
+    protected $signature = "toby:move-user-data-to-profile";
+    protected $description = "Move user data to their profiles";
+
+    public function handle(): void
+    {
+        $users = User::all();
+
+        /** @var User $user */
```
Comment (krzysztofrewak) [inline app/Infrastructure/Console/Commands/MoveUserDataToProfile.php:19]: Do we need this docblock with these here https://github.com/illuminate/collections/blob/master/Collection.php#L60 ?

File: app/Infrastructure/Http/Middleware/HandleInertiaRequests.php [hunk 4]
```diff
@@ -17,25 +19,55 @@ public function __construct(
...
+        return fn() => [
+            "success" => $request->session()->get("success"),
+            "error" => $request->session()->get("error"),
+            "info" => $request->session()->get("info"),
+        ];
+    }
+
+    protected function getYearsData(Request $request): Closure
+    {
+        return fn() => $request->user() ? $this->yearPeriodRetriever->links() : [];
```
Comment (krzysztofrewak) [inline app/Infrastructure/Http/Middleware/HandleInertiaRequests.php:57]:
```suggestion
        return fn(): array => $request->user() ? $this->yearPeriodRetriever->links() : [];
```

File: app/Infrastructure/Http/Middleware/HandleInertiaRequests.php [hunk 5]
```diff
@@ -17,25 +19,55 @@ public function __construct(
...
+    }
+
+    protected function getVacationRequestsCount(Request $request): Closure
+    {
+        $user = $request->user();
+
+        return fn() => $user && $user->can("listAll", VacationRequest::class)
```
Comment (krzysztofrewak) [inline app/Infrastructure/Http/Middleware/HandleInertiaRequests.php:64]:
```suggestion
        return fn(): ?int => $user && $user->can("listAll", VacationRequest::class)
```

File: resources/js/app.js [hunk 6]
```diff
@@ -44,3 +46,4 @@ Flatpickr.setDefaults({
   disableMobile: true,
 })
 
+Settings.defaultLocale = 'pl'
```
Comment (EwelinaLasowy) [inline resources/js/app.js:49]:
```suggestion
Settings.defaultLocale = 'pl'

```

**Review by krzysztofrewak — CHANGES_REQUESTED** [review]

File: resources/js/Shared/InertiaLink.js [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+          if (shouldIntercept(event)) {
+            event.preventDefault()
+
+            Inertia.visit(href, {
+              data: data,
+              method: method,
+              replace: props.replace,
+              preserveScroll: props.preserveScroll,
+              preserveState: props.preserveState ?? (method !== 'get'),
+              onBefore: () => ! processing.value,
```
Comment (krzysztofrewak) [inline resources/js/Shared/InertiaLink.js:56]:
```suggestion
              onBefore: () => !processing.value,
```

:eyes:

**Review by krzysztofrewak — CHANGES_REQUESTED** [review]

**Review by EwelinaLasowy — APPROVED** [review]
